spack:
  concretizer:
    unify: false
    reuse: false
  view: false
  specs:
    - pelec+hdf5+masa%gcc
    - pelelmex+hdf5%gcc
    - pelec+hdf5+cuda%gcc cuda_arch=80
    - pelelmex+hdf5+cuda%gcc cuda_arch=80
    - pelec+hdf5+masa+asan%llvm
    - pelelmex+hdf5+asan%llvm
    - pelec+hdf5+masa%llvm
    - pelelmex+hdf5%llvm
