spack:
  concretizer:
    unify: false
    reuse: false
  view: false
  specs:
    - pelec%gcc
    - pelelmex%gcc
    - pelec+cuda%gcc cuda_arch=80
    - pelelmex+cuda%gcc cuda_arch=80
    - pelec+asan%clang
    - pelelmex+asan%clang
    - pelec%clang
    - pelelmex%clang
