compilers:
  - compiler:
      spec: gcc@12.3.0
      paths:
        cc: /nopt/nrel/apps/gpu_stack/compilers/06-24/linux-rhel8-zen4/gcc-12.3.0/gcc-12.3.0-bwbarmbu4cyrk36bzl62iteel6dnsr5r/bin/gcc
        cxx: /nopt/nrel/apps/gpu_stack/compilers/06-24/linux-rhel8-zen4/gcc-12.3.0/gcc-12.3.0-bwbarmbu4cyrk36bzl62iteel6dnsr5r/bin/g++
        f77: /nopt/nrel/apps/gpu_stack/compilers/06-24/linux-rhel8-zen4/gcc-12.3.0/gcc-12.3.0-bwbarmbu4cyrk36bzl62iteel6dnsr5r/bin/gfortran
        fc: /nopt/nrel/apps/gpu_stack/compilers/06-24/linux-rhel8-zen4/gcc-12.3.0/gcc-12.3.0-bwbarmbu4cyrk36bzl62iteel6dnsr5r/bin/gfortran
      flags: {}
      operating_system: rhel8
      target: x86_64
      modules:
        - openmpi/main-gpu
        - libfabric/lnx
      extra_rpaths: []
      environment: {}
