packages:
  gcc:
    externals:
      - spec: gcc@12.2.1
        prefix: /opt/rh/gcc-toolset-12/root/usr
        extra_attributes:
          compilers:
            c: /opt/rh/gcc-toolset-12/root/usr/bin/gcc
            cxx: /opt/rh/gcc-toolset-12/root/usr/bin/g++
            fortran: /opt/rh/gcc-toolset-12/root/usr/bin/gfortran
  cray-mpich:
    require: "@8.1.32"
    buildable: false
    externals:
      - spec: "cray-mpich@8.1.32%gcc@12.2.1"
        prefix: /projects/hpcapps/cray0425/8.1.32/mpich/8.1.32/ofi
        modules:
          - libfabric/1.15.2.0
  cuda:
    require: "@=12.4.1"
  boost:
    require: "@=1.80.0"
  mpi:
    require: "cray-mpich@8.1.32"
  blas:
    require: "netlib-lapack"
  lapack:
    require: "netlib-lapack"
  c:
    require: "gcc@12.2.1"
  cxx:
    require: "gcc@12.2.1"
  fortran:
    require: "gcc@12.2.1"
  all:
    prefer:
      - "build_type=Release"
      - "cuda_arch=90"
