packages:
  gcc:
    externals:
      - spec: gcc@12.3.0
        prefix: /nopt/nrel/apps/gpu_stack/compilers/06-24/linux-rhel8-zen4/gcc-12.3.0/gcc-12.3.0-bwbarmbu4cyrk36bzl62iteel6dnsr5r
        extra_attributes:
          compilers:
            c: /nopt/nrel/apps/gpu_stack/compilers/06-24/linux-rhel8-zen4/gcc-12.3.0/gcc-12.3.0-bwbarmbu4cyrk36bzl62iteel6dnsr5r/bin/gcc
            cxx: /nopt/nrel/apps/gpu_stack/compilers/06-24/linux-rhel8-zen4/gcc-12.3.0/gcc-12.3.0-bwbarmbu4cyrk36bzl62iteel6dnsr5r/bin/g++
            fortran: /nopt/nrel/apps/gpu_stack/compilers/06-24/linux-rhel8-zen4/gcc-12.3.0/gcc-12.3.0-bwbarmbu4cyrk36bzl62iteel6dnsr5r/bin/gfortran
  cray-mpich:
    require: "@9.0.0"
    buildable: false
    externals:
      - spec: "cray-mpich@9.0.0%gcc@12.3.0"
        prefix: /kfs2/projects/hpcapps/cray0425/9.0.0/mpich-gcc
        modules:
          - mpich_gcc
          - libfabric/lnx
  cuda:
    require: "@=12.4.1"
  boost:
    require: "@=1.80.0"
  mpi:
    require: "cray-mpich@9.0.0"
  blas:
    require: "netlib-lapack"
  lapack:
    require: "netlib-lapack"
  c:
    require: "gcc@12.3.0"
  cxx:
    require: "gcc@12.3.0"
  fortran:
    require: "gcc@12.3.0"
  all:
    prefer:
      - "build_type=Release"
      - "cuda_arch=90"
