packages:
  openmpi:
    require: "@=5.1"
    buildable: false
    externals:
      - spec: "openmpi@=5.1%gcc@12.3.0"
        prefix: /kfs2/projects/hpcapps/warsalan/libfabric/gpu_04-25/ompi/build
        modules:
          - openmpi/main-gpu
  cuda:
    require: "@=12.3"
    buildable: false
    externals:
      - spec: "cuda@=12.3%gcc@12.3.0"
        prefix: /nopt/cuda/12.3
        modules:
          - cuda/12.3
  boost:
    require: "@=1.80.0"
  mpi:
    require: "openmpi@5.1"
  blas:
    require: "netlib-lapack"
  lapack:
    require: "netlib-lapack"
  all:
    prefer:
      - "%gcc"
      - "build_type=Release"
      - "cuda_arch=90"
