packages:
  cmake:
    require: "@=4.0.1"
    buildable: false
    externals:
      - spec: "cmake@4.0.1"
        prefix: /opt/homebrew/Cellar/cmake/4.0.1
  mpi:
    require: "mpich"
  blas:
    require: "openblas"
  lapack:
    require: "openblas"
  c:
    require: "apple-clang"
  cxx:
    require: "apple-clang"
  fortran:
    require: "gcc"
